version: "3.9"

services:
  dev:
    container_name: "${COMPOSE_PROJECT_NAME}"
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    image: "${COMPOSE_PROJECT_NAME}"
    user: pn
    environment:
      AWS_CONFIG_FILE: /aws-config
      AWS_DEFAULT_REGION: eu-central-1
    volumes:
      - "${AWS_CONFIG_FILE}:/aws-config:ro"
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - .:/app
